version: '3.7'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres.occbjwzbvvdubfwrxlot:!8r9b*P!XSSkqCk@aws-0-eu-central-1.pooler.supabase.com:6543/postgres
